# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [6]:
# Import torch
import torch

# Create random tensor
random_tensor_a = torch.randn(size=(7, 7))

print("random_tensor_a:")
print(random_tensor_a)

print(f"random_tensor_a.shape: {random_tensor_a.shape}\n")

random_tensor_b = torch.arange(start=1, end=50, step=1).reshape(7, 7)

print("random_tensor_b:")
print(random_tensor_b)

print(f"random_tensor_b.shape: {random_tensor_b.shape}\n")


random_tensor_a:
tensor([[-0.3432,  2.1356, -0.1584, -0.8125,  0.0028, -0.6783,  0.3799],
        [ 0.5683, -0.5024,  1.8323, -1.3825, -0.7633,  1.4112, -0.4104],
        [ 0.3013,  0.7772, -0.8505, -0.1739, -1.5348, -0.4038, -1.1126],
        [-0.2722, -0.2351, -1.0506,  1.0228, -1.2736, -1.1387,  0.6499],
        [ 1.0176, -0.5675,  0.5765, -2.2834,  0.2000,  0.1851, -1.3433],
        [-0.1766, -1.0532,  0.0866,  0.7402,  0.7462,  0.2320,  0.4223],
        [ 0.6250,  0.0366,  0.4307,  0.0282,  0.5371, -2.0286,  0.4218]])
random_tensor_a.shape: torch.Size([7, 7])

random_tensor_b:
tensor([[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28],
        [29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48, 49]])
random_tensor_b.shape: torch.Size([7, 7])



### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor
another_random_tensor = torch.rand(size=(1, 7))

print("another_random_tensor:")
print(another_random_tensor)

print(f"another_random_tensor.shape: {another_random_tensor.shape}\n")

# Perform matrix multiplication
resulted_matrix = torch.matmul(random_tensor_a, another_random_tensor.T)

print("resulted_matrix:")
print(resulted_matrix)

print(f"resulted_matrix.shape: {resulted_matrix.shape}\n")

another_random_tensor:
tensor([[0.5790, 0.6418, 0.2740, 0.1479, 0.9485, 0.8549, 0.6659]])
another_random_tensor.shape: torch.Size([1, 7])

resulted_matrix:
tensor([[ 0.6841],
        [ 0.5133],
        [-2.1274],
        [-2.1938],
        [-0.5014],
        [ 0.5424],
        [-0.4364]])
resulted_matrix.shape: torch.Size([7, 1])



### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [17]:
# (Added by Me): Importing the 'random' library
import random

# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)

# Create two random tensors
first_random_tensor = torch.randn(size=(7, 7))

# (Added by Me): Set manual seed again
torch.random.manual_seed(seed=RANDOM_SEED)

second_random_tensor = torch.randn(size=(1, 7))

# (Added by Me): Matrix Multiplication Rule
if (first_random_tensor.shape[1] == second_random_tensor.shape[0]):
    print("These matrices can be multiplied.")
else:
    print("These matrices cannot be multiplied.")


# Matrix multiply tensors
second_random_tensor = second_random_tensor.T

result = torch.matmul(first_random_tensor, second_random_tensor)

print(result, result.shape)

These matrices cannot be multiplied.
tensor([[-3.1132],
        [-0.4052],
        [ 2.2938],
        [-4.9556],
        [-0.9954],
        [ 1.9452],
        [ 2.2410]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed


# Check for access to GPU

# Create two random tensors on GPU



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
